### ISSUE TITLE
cljr-create-fn-from-example throws "Symbol’s function definition is void: seq-map-indexed"

### ISSUE THREAD

**Issue by olessavluk** [clojure-emacs/clj-refactor.el#365]
## Expected behavior
`cljr-create-fn-from-example` should work

## Actual behavior
I see `cljr--insert-example-fn: Symbol’s function definition is void: seq-map-indexed` in *Messages*

## Steps to reproduce the problem
type `(test 1 2 3)` and then run `cljr-create-fn-from-example`

## Environment & Version information
<details>
### clj-refactor.el version information
```
clj-refactor 2.3.0-SNAPSHOT (package: 20170126.118), refactor-nrepl 2.3.0-SNAPSHOT
```

### CIDER version information
```
;; CIDER 0.15.0snapshot (package: 20170304.2330), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_66
```

### Leiningen or Boot version
```
Leiningen 2.7.1 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM
```

### Emacs version
```
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-21
```
emacs.d - https://github.com/olessavluk/emacs.d/commit/65299ac88dd77a0e1066a1b4d9c06774f5a0a303

### Operating system
```
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
```
</details>

**Comment by olessavluk** [comment]
### Own attempt to debug

I tried to run `seq-map-indexed` in my *scratch* buffer and it has some strange behavior:

```elisp
(require 'seq)
(seq-map '+ '(1 2 3)) ;; => (1 2 3)
(seq-map-indexed '+ '(1 2 3) ;; => (void-function seq-map-indexed)
```

But if I require `'seq-25` or just copy-paste content of `seq.el` - everything works fine, and even clj-refactor start working:
```elisp
(if (version< emacs-version "25")
    (require 'seq-24)
  (require 'seq-25)) ;; => seq-25

(seq-map '+ '(1 2 3)) ;; => (1 2 3)
(seq-map-indexed '+ '(1 2 3)) ;; => (void-function seq-map-indexed)
```

So it looks like `seq.el` is "broken" or not being properly required?

**Comment by expez** [comment]
I've seen this in the past, when upgrading clj-refactor to the first version without `dash.el`.  What I found, when I did `M-x find-libarary <RET> seq <RET>`, was that the library version loaded wasn't the correct one.  It was some old `seq.el` pulled down using the package manager.

I fixed this by just deleting `seq.el` and `clj-refactor` and re-installing using the package manager.

**Comment by olessavluk** [comment]
Tried to reinstall everything - still the same

In the `elpa` folder, seems like I have the newest packages:
`clj-refactor-20170126.118`
`seq-2.19` <- `find-library` also opens the newest version
`dash-20170207.2056`

But what I have found is that emacs have it's own bundled `seq` v2.3 which is being resolved instead of library from melpa. And I can't understand why:

```elisp
load-path ;; =>
;; "/Users/olessavluk/.emacs.d/elpa/clj-refactor-20170126.118"
;; ...
;; "/Users/olessavluk/.emacs.d/elpa/seq-2.19"
;; ...
;; "/Users/olessavluk/.emacs.d/lisp"
;; "/Library/Application Support/Emacs/25.1/site-lisp"
;; "/Library/Application Support/Emacs/site-lisp"
;; "/Applications/Emacs.app/Contents/Resources/site-lisp"
;; "/Applications/Emacs.app/Contents/Resources/lisp"
;; "/Applications/Emacs.app/Contents/Resources/lisp/vc"
;; ...
;; "/Applications/Emacs.app/Contents/Resources/lisp/calc"
;; "/Applications/Emacs.app/Contents/Resources/lisp/obsolete"

(locate-library "seq") ;; => "/Users/olessavluk/.emacs.d/elpa/seq-2.19/seq.elc"

(list-load-path-shadows) ;; =>
;; /Users/olessavluk/.emacs.d/elpa/seq-2.19/seq hides /Applications/Emacs.app/Contents/Resources/lisp/emacs-lisp/seq
;;
;; 1 Emacs Lisp load-path shadowing was found

(require 'seq) ;; => seq # but should be seq-25
(seq-map-indexed) ;; => (void-function seq-map-indexed)
```

Looks like an emacs issue, right?

**Comment by expez** [comment]
> Looks like an emacs issue, right?

Yes, or something related to your config at least.

Unfortunately there's nothing we can do about this, so I'm glad you found a workaround!

**Comment by benedekfazekas** [comment]
this has bitten me lately too. i guess this commit explains the situation https://github.com/NicolasPetton/Indium/commit/3e41fa6f132f2b3130d9abd250a52cfea7655d17
